export const feedData = [
  {
    id: 1,
    username: "john_doe",
    profileImage: "https://randomuser.me/api/portraits/men/32.jpg",
    postImage: "https://picsum.photos/id/237/600/600",
    caption: "Exploring the mountains 🏔️ #adventure",
    likes: 120,
    comments: [
      { id: 1, username: "nature_nerd", text: "So beautiful!" },
      { id: 2, username: "travel_junkie", text: "I want to go there 😍" },
    ],
    isLiked: false,
  },
  {
    id: 2,
    username: "jane_smith",
    profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
    postImage: "https://picsum.photos/id/1025/600/600",
    caption: "Coffee + Coding = ❤️ #devlife",
    likes: 95,
    comments: [{ id: 1, username: "code_master", text: "Same here ☕👨‍💻" }],
    isLiked: true,
  },
  {
    id: 3,
    username: "foodie_life",
    profileImage: "https://randomuser.me/api/portraits/women/28.jpg",
    postImage: "https://picsum.photos/id/1080/600/600",
    caption: "Brunch done right 🍳🥑",
    likes: 210,
    comments: [
      { id: 1, username: "chef_jake", text: "Looks delicious!" },
      { id: 2, username: "hungry_now", text: "YUM!" },
    ],
    isLiked: false,
  },
  {
    id: 4,
    username: "cat_lover",
    profileImage: "https://randomuser.me/api/portraits/women/63.jpg",
    postImage: "https://picsum.photos/id/100/600/600",
    caption: "Just me and my little furball 🐱",
    likes: 180,
    comments: [{ id: 1, username: "dog_dad", text: "Cute overload 😍" }],
    isLiked: true,
  },
  {
    id: 5,
    username: "skyline_views",
    profileImage: "https://randomuser.me/api/portraits/men/54.jpg",
    postImage: "https://picsum.photos/id/1012/600/600",
    caption: "City lights never sleep ✨",
    likes: 300,
    comments: [
      { id: 1, username: "nightcrawler", text: "Insane view!" },
      { id: 2, username: "photo_freak", text: "What camera? 📸" },
    ],
    isLiked: false,
  },
];
