export const storiesData = [
  {
    id: 1,
    username: "john_doe",
    profileImage: "https://randomuser.me/api/portraits/men/32.jpg",
    isSeen: false,
  },
  {
    id: 2,
    username: "jane_smith",
    profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
    isSeen: true,
  },
  {
    id: 3,
    username: "cat_lover",
    profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
    isSeen: false,
  },
  {
    id: 4,
    username: "travel_junkie",
    profileImage: "https://randomuser.me/api/portraits/men/78.jpg",
    isSeen: false,
  },
  {
    id: 5,
    username: "foodie_life",
    profileImage: "https://randomuser.me/api/portraits/women/28.jpg",
    isSeen: true,
  },
  {
    id: 6,
    username: "skyline_views",
    profileImage: "https://randomuser.me/api/portraits/men/54.jpg",
    isSeen: false,
  },
  {
    id: 7,
    username: "art_addict",
    profileImage: "https://randomuser.me/api/portraits/women/63.jpg",
    isSeen: true,
  },
  {
    id: 8,
    username: "daily_runner",
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
    isSeen: false,
  },
  {
    id: 9,
    username: "sunshine_girl",
    profileImage: "https://randomuser.me/api/portraits/women/34.jpg",
    isSeen: true,
  },
  {
    id: 10,
    username: "fitness_freak",
    profileImage: "https://randomuser.me/api/portraits/men/12.jpg",
    isSeen: false,
  },
  {
    id: 11,
    username: "bookworm23",
    profileImage: "https://randomuser.me/api/portraits/women/19.jpg",
    isSeen: true,
  },
  {
    id: 12,
    username: "beach_babe",
    profileImage: "https://randomuser.me/api/portraits/women/88.jpg",
    isSeen: false,
  },
  {
    id: 13,
    username: "adventure_dude",
    profileImage: "https://randomuser.me/api/portraits/men/10.jpg",
    isSeen: false,
  },
  {
    id: 14,
    username: "coffee_addict",
    profileImage: "https://randomuser.me/api/portraits/women/51.jpg",
    isSeen: true,
  },
  {
    id: 15,
    username: "nature_nerd",
    profileImage: "https://randomuser.me/api/portraits/men/60.jpg",
    isSeen: false,
  },
  {
    id: 16,
    username: "makeup_maven",
    profileImage: "https://randomuser.me/api/portraits/women/72.jpg",
    isSeen: true,
  },
  {
    id: 17,
    username: "code_master",
    profileImage: "https://randomuser.me/api/portraits/men/25.jpg",
    isSeen: false,
  },
  {
    id: 18,
    username: "mom_life",
    profileImage: "https://randomuser.me/api/portraits/women/44.jpg",
    isSeen: true,
  },
  {
    id: 19,
    username: "car_guy",
    profileImage: "https://randomuser.me/api/portraits/men/8.jpg",
    isSeen: false,
  },
  {
    id: 20,
    username: "plant_mom",
    profileImage: "https://randomuser.me/api/portraits/women/5.jpg",
    isSeen: false,
  },
  {
    id: 21,
    username: "music_junkie",
    profileImage: "https://randomuser.me/api/portraits/men/16.jpg",
    isSeen: true,
  },
  {
    id: 22,
    username: "photo_freak",
    profileImage: "https://randomuser.me/api/portraits/women/7.jpg",
    isSeen: false,
  },
  {
    id: 23,
    username: "dog_dad",
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    isSeen: true,
  },
  {
    id: 24,
    username: "biker_queen",
    profileImage: "https://randomuser.me/api/portraits/women/36.jpg",
    isSeen: false,
  },
  {
    id: 25,
    username: "lazy_lad",
    profileImage: "https://randomuser.me/api/portraits/men/90.jpg",
    isSeen: false,
  },
];
